'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import {
  FileCheck2,
  FileDown,
  RefreshCw,
  Building2,
  Clock,
  ExternalLink,
  ShieldCheck
} from 'lucide-react';
import { api } from '@/services/api';

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const data = await api.getReports();
      setReports(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900">Official Verification Dossiers & Reports</h2>
          <p className="text-xs text-slate-500 mt-1">
            Publication-grade PDF reports generated using ReportLab, containing full audit hashes, scoring gauges, and verification matrices.
          </p>
        </div>

        <button
          onClick={fetchReports}
          className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl border border-slate-300 text-slate-700 hover:bg-slate-50 text-xs font-semibold"
        >
          <RefreshCw className="h-3.5 w-3.5" /> Refresh Archive
        </button>
      </div>

      <div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden">
        {loading ? (
          <div className="py-16 text-center text-xs font-semibold text-slate-500 flex flex-col items-center gap-2">
            <RefreshCw className="h-6 w-6 animate-spin text-emerald-600" />
            Loading reports archive...
          </div>
        ) : reports.length === 0 ? (
          <div className="py-16 text-center text-slate-400 text-xs">
            <FileCheck2 className="h-8 w-8 mx-auto text-slate-300 mb-2" />
            No reports generated yet. Go to any vendor page and click &quot;Download Official PDF Report&quot;.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 text-slate-500 uppercase tracking-wider border-b border-slate-200 font-semibold">
                <tr>
                  <th className="py-3.5 px-4">Report Reference</th>
                  <th className="py-3.5 px-4">Vendor Entity</th>
                  <th className="py-3.5 px-4">Compliance / Risk</th>
                  <th className="py-3.5 px-4">Generated By</th>
                  <th className="py-3.5 px-4">Timestamp</th>
                  <th className="py-3.5 px-4 text-right">Download</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-medium">
                {reports.map((r) => (
                  <tr key={r.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="py-3.5 px-4 font-mono font-bold text-slate-900">
                      {r.report_id}
                    </td>
                    <td className="py-3.5 px-4 font-semibold text-slate-800">
                      <Link href={`/vendors/${r.vendor_id}`} className="hover:text-emerald-600 flex items-center gap-1.5">
                        <Building2 className="h-3.5 w-3.5 text-slate-400" />
                        {r.vendor_name}
                      </Link>
                    </td>
                    <td className="py-3.5 px-4">
                      <div className="text-slate-900 font-semibold">Compliance: {r.compliance_score.toFixed(0)}%</div>
                      <div className="text-slate-500 text-[10px]">Risk: {r.risk_score.toFixed(0)}%</div>
                    </td>
                    <td className="py-3.5 px-4 text-slate-600">{r.generated_by}</td>
                    <td className="py-3.5 px-4 text-slate-400">
                      {new Date(r.generated_at).toLocaleString()}
                    </td>
                    <td className="py-3.5 px-4 text-right">
                      <a
                        href={api.getReportDownloadUrl(r.vendor_id)}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-emerald-50 hover:bg-emerald-100 text-emerald-700 font-bold text-[11px] transition-colors border border-emerald-200"
                      >
                        <FileDown className="h-3.5 w-3.5" /> PDF Dossier
                      </a>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
