import os
from datetime import datetime, timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)
from backend.config import Config
from backend.models.models import Bid, AuditLog


def generate_compliance_pdf_report(bid: Bid, report_code: str, generated_by_user=None) -> str:
    """
    Generates a downloadable enterprise/government-grade PDF Compliance Verification Report
    using ReportLab. Returns the absolute path to the generated PDF file.
    """
    os.makedirs(Config.REPORTS_FOLDER, exist_ok=True)
    filename = f"{report_code}_{bid.bid_number.replace('/', '-')}.pdf"
    file_path = os.path.join(Config.REPORTS_FOLDER, filename)

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
        title=f"BidVerify Compliance Report - {report_code}",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=15,
        leading=19,
        textColor=colors.HexColor("#0f2942"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "ReportSub",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#475569"),
        spaceAfter=8,
    )
    section_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#0f2942"),
        spaceBefore=10,
        spaceAfter=6,
    )
    cell_style = ParagraphStyle(
        "CellText",
        parent=styles["Normal"],
        fontSize=8,
        leading=10.5,
        textColor=colors.HexColor("#1e293b"),
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#7c2d12"),
        backColor=colors.HexColor("#fff7ed"),
        borderPadding=6,
        spaceAfter=10,
    )

    elements = []
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Header
    elements.append(Paragraph("GOVERNMENT e-MARKETPLACE (GeM) PROCUREMENT DECISION-SUPPORT", subtitle_style))
    elements.append(Paragraph("BID COMPLIANCE VERIFICATION REPORT", title_style))
    elements.append(
        Paragraph(
            f"<b>Report ID:</b> {report_code} &nbsp;&nbsp;|&nbsp;&nbsp; "
            f"<b>Generated On:</b> {now_str} &nbsp;&nbsp;|&nbsp;&nbsp; "
            f"<b>Generated By:</b> {generated_by_user.full_name if generated_by_user else 'Authorized Procurement Officer'}",
            subtitle_style,
        )
    )
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceAfter=8))

    # Mandatory Decision-Support Notice
    elements.append(
        Paragraph(
            "<b>IMPORTANT STATUTORY NOTICE (DECISION-SUPPORT ONLY):</b> This AI-assisted compliance verification report "
            "extracts document evidence, compares tender requirements, and highlights potential anomalies for officer review. "
            "It does NOT automatically select a winning bidder or constitute a final procurement award/rejection decision. "
            "Final decision authority rests exclusively with the authorized Procurement Officer.",
            disclaimer_style,
        )
    )

    tender = bid.tender
    company = bid.company

    # 1. Tender & Bidder Information
    elements.append(Paragraph("1. Tender & Bidder Information", section_style))
    info_data = [
        [
            Paragraph("<b>Tender Code</b>", cell_style),
            Paragraph(str(tender.tender_code if tender else "N/A"), cell_style),
            Paragraph("<b>Bid Number</b>", cell_style),
            Paragraph(str(bid.bid_number), cell_style),
        ],
        [
            Paragraph("<b>Tender Title</b>", cell_style),
            Paragraph(str(tender.title if tender else "N/A"), cell_style),
            Paragraph("<b>Bidder / Company</b>", cell_style),
            Paragraph(str(company.company_name if company else "N/A"), cell_style),
        ],
        [
            Paragraph("<b>Department</b>", cell_style),
            Paragraph(str(tender.department if tender else "N/A"), cell_style),
            Paragraph("<b>GSTIN / PAN</b>", cell_style),
            Paragraph(f"{company.gstin if company else 'N/A'} / {company.pan if company else 'N/A'}", cell_style),
        ],
        [
            Paragraph("<b>Estimated Value</b>", cell_style),
            Paragraph(f"INR {tender.estimated_value:,.2f}" if tender and tender.estimated_value else "N/A", cell_style),
            Paragraph("<b>Quoted Bid Amount</b>", cell_style),
            Paragraph(f"INR {bid.quoted_amount:,.2f}", cell_style),
        ],
        [
            Paragraph("<b>Product Offered</b>", cell_style),
            Paragraph(f"{bid.product_name or 'N/A'} ({bid.product_model or 'Standard'})", cell_style),
            Paragraph("<b>Udyam / MSME ID</b>", cell_style),
            Paragraph(str(company.udyam_number if company and company.udyam_number else "N/A"), cell_style),
        ],
    ]
    info_table = Table(info_data, colWidths=[32 * mm, 58 * mm, 32 * mm, 58 * mm])
    info_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
            ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#f1f5f9")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 5),
        ])
    )
    elements.append(info_table)

    # 2. Compliance Score & Risk Summary
    elements.append(Paragraph("2. Compliance Score & Risk Level Summary", section_style))
    score_data = [
        [
            Paragraph("<b>Document Compliance</b>", cell_style),
            Paragraph("<b>Statutory Compliance</b>", cell_style),
            Paragraph("<b>Technical Compliance</b>", cell_style),
            Paragraph("<b>Tender Policy Compliance</b>", cell_style),
            Paragraph("<b>Overall Score</b>", cell_style),
            Paragraph("<b>Risk Level</b>", cell_style),
        ],
        [
            Paragraph(f"{bid.document_compliance_score:.1f}%", cell_style),
            Paragraph(f"{bid.statutory_compliance_score:.1f}%", cell_style),
            Paragraph(f"{bid.technical_compliance_score:.1f}%", cell_style),
            Paragraph(f"{bid.tender_compliance_score:.1f}%", cell_style),
            Paragraph(f"<b>{bid.overall_compliance_score:.1f}%</b>", cell_style),
            Paragraph(f"<b>{bid.risk_level}</b>", cell_style),
        ],
    ]
    score_table = Table(score_data, colWidths=[30 * mm, 30 * mm, 30 * mm, 32 * mm, 28 * mm, 30 * mm])
    score_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f2942")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("PADDING", (0, 0), (-1, -1), 5),
        ])
    )
    # Fix header text color in Paragraph
    for col_i in range(6):
        score_data[0][col_i] = Paragraph(
            score_data[0][col_i].text,
            ParagraphStyle("Hdr", parent=cell_style, textColor=colors.white),
        )
    score_table = Table(score_data, colWidths=[30 * mm, 30 * mm, 30 * mm, 32 * mm, 28 * mm, 30 * mm])
    score_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f2942")),
            ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("PADDING", (0, 0), (-1, -1), 5),
        ])
    )
    elements.append(score_table)

    # 3. Documents Processed
    elements.append(Paragraph("3. Uploaded Documents & OCR Classification", section_style))
    doc_rows = [[
        Paragraph("<font color='white'><b>Filename</b></font>", cell_style),
        Paragraph("<font color='white'><b>Declared Type</b></font>", cell_style),
        Paragraph("<font color='white'><b>AI Detected Category</b></font>", cell_style),
        Paragraph("<font color='white'><b>OCR Pipeline</b></font>", cell_style),
        Paragraph("<font color='white'><b>Status</b></font>", cell_style),
    ]]
    for d in bid.documents:
        doc_rows.append([
            Paragraph(str(d.original_filename), cell_style),
            Paragraph(str(d.declared_doc_type or "N/A"), cell_style),
            Paragraph(f"{d.detected_doc_type} ({int((d.classification_confidence or 0.9)*100)}%)", cell_style),
            Paragraph(f"{d.ocr_engine_used or 'EasyOCR'}" + (f" ({int(d.ocr_confidence*100)}%)" if d.ocr_confidence else ""), cell_style),
            Paragraph(str(d.processing_status), cell_style),
        ])
    if len(doc_rows) == 1:
        doc_rows.append([Paragraph("No documents uploaded", cell_style), Paragraph("-"), Paragraph("-"), Paragraph("-"), Paragraph("-")])

    doc_table = Table(doc_rows, colWidths=[44 * mm, 32 * mm, 42 * mm, 40 * mm, 22 * mm])
    doc_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 4),
        ])
    )
    elements.append(doc_table)

    # 4. Detailed Compliance Checks & Supporting Evidence
    elements.append(Paragraph("4. Compliance Verification Checks & Supporting Evidence", section_style))
    chk_rows = [[
        Paragraph("<font color='white'><b>Check / Category</b></font>", cell_style),
        Paragraph("<font color='white'><b>Requirement</b></font>", cell_style),
        Paragraph("<font color='white'><b>Submitted / Extracted</b></font>", cell_style),
        Paragraph("<font color='white'><b>Status</b></font>", cell_style),
        Paragraph("<font color='white'><b>Evidence & Explanation</b></font>", cell_style),
    ]]
    for c in bid.compliance_results:
        ev_text = c.reason or ""
        if c.evidence_items:
            ev0 = c.evidence_items[0]
            ev_text = f"<b>[{ev0.document_name}, Page {ev0.page_number}]</b> {c.reason}"
        chk_rows.append([
            Paragraph(f"<b>{c.check_name}</b><br/><font size='7' color='#64748b'>{c.category}</font>", cell_style),
            Paragraph(str(c.requirement_text or "-"), cell_style),
            Paragraph(str(c.submitted_text or "-"), cell_style),
            Paragraph(f"<b>{c.status}</b>", cell_style),
            Paragraph(ev_text, cell_style),
        ])
    if len(chk_rows) == 1:
        chk_rows.append([Paragraph("No checks executed yet", cell_style), Paragraph("-"), Paragraph("-"), Paragraph("-"), Paragraph("-")])

    chk_table = Table(chk_rows, colWidths=[36 * mm, 34 * mm, 32 * mm, 24 * mm, 54 * mm])
    chk_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 4),
        ])
    )
    elements.append(chk_table)

    # 5. AI / ML Isolation Forest Risk & Anomaly Analysis
    elements.append(Paragraph("5. AI / ML Risk & Anomaly Analysis (Scikit-learn Isolation Forest)", section_style))
    latest_risk = bid.risk_results[-1] if bid.risk_results else None
    if latest_risk:
        r_dict = latest_risk.to_dict()
        elements.append(
            Paragraph(
                f"<b>Risk Level:</b> {r_dict['risk_level']} &nbsp;|&nbsp; "
                f"<b>Composite Risk Score:</b> {r_dict['risk_score']}/100 &nbsp;|&nbsp; "
                f"<b>Isolation Forest Anomaly Score:</b> {r_dict['anomaly_score']} &nbsp;|&nbsp; "
                f"<b>Anomaly Flag:</b> {'Potential Anomaly -> Human Review Required' if r_dict['is_anomaly_flagged'] else 'Normal Range'}",
                cell_style,
            )
        )
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(f"<b>ML Explanation:</b> {r_dict['ml_explanation']}", cell_style))
        elements.append(Spacer(1, 4))
        for rf in r_dict.get("risk_factors", []):
            elements.append(
                Paragraph(f"&bull; <b>[{rf.get('severity')} - {rf.get('category')}]</b> {rf.get('factor')}", cell_style)
            )
    else:
        elements.append(Paragraph("Risk analysis has not been run on this bid yet.", cell_style))

    # 6. Human Review & Officer Decision-Support Record
    elements.append(Paragraph("6. Authorized Procurement Officer Human Review", section_style))
    elements.append(
        Paragraph(
            f"<b>Officer Review Status:</b> {bid.officer_review_status} &nbsp;&nbsp;|&nbsp;&nbsp; "
            f"<b>Reviewed At:</b> {bid.reviewed_at.isoformat() if bid.reviewed_at else 'Pending Officer Action'}<br/>"
            f"<b>Officer Review Comments:</b> {bid.officer_review_comments or 'No manual review remarks recorded yet.'}",
            cell_style,
        )
    )

    # 7. Recent Audit Trail Entries for this Bid
    elements.append(Paragraph("7. Verification Audit Trail", section_style))
    logs = AuditLog.query.filter_by(bid_id=bid.id).order_by(AuditLog.timestamp.desc()).limit(6).all()
    for lg in logs:
        ts = lg.timestamp.strftime("%Y-%m-%d %H:%M:%S") if lg.timestamp else ""
        elements.append(
            Paragraph(
                f"&bull; <b>{ts}</b> | {lg.user_name} ({lg.user_role}) &rarr; <b>{lg.action}</b> [{lg.result_status}]",
                cell_style,
            )
        )

    doc.build(elements)
    return file_path
